import {
   ForeignKeyFields,
   GetModels,
   RelationFields,
   ScalarFields,
   SchemaDef,
} from "@zenstackhq/schema";
import { Type } from "@nestjs/common";
import { PrimaryKeyFields, TypeWithKeys } from "./types";
import { OmitRelations } from "./omit-relations";
import { OnlyRelations } from "./only-relations";
import { OnlyScalars } from "./only-scalars";
import { OmitScalars } from "./omit-scalars";
import { OmitFK } from "./omit-fk";
import { OnlyFK } from "./only-fk";
import { OmitComputed } from "./omit-computed";
import { OmitAutoGenerated } from "./omit-auto-generated";
import { OmitPK } from "./omit-pk";
import { OnlyPK } from "./only-pk";
import { CreateType } from "./create-type";
import { UpdateType } from "./update-type";
import { chain } from "./chain";

/**
 * A schema-aware mapped-type factory: `(schema, model, dto) => Type<…>`.
 * Pass these into {@link CreateMappedTypes} as custom (or overriding) helpers.
 *
 * Parameters after `schema` are typed loosely so inline lambdas get contextual
 * typing and both generic helpers (`OmitPK`) and custom factories are accepted.
 *
 * @typeParam Schema - ZenStack schema definition.
 */
export type SchemaMappedTypeFn<Schema extends SchemaDef = SchemaDef> = (
   schema: Schema,
   model: any,
   dto: any,
) => Type<any>;

/**
 * Schema-bound helper returned by {@link CreateMappedTypes}: `(model, dto) => Type<…>`.
 *
 * @typeParam Schema - ZenStack schema definition.
 */
export type BoundMappedTypeFn<Schema extends SchemaDef = SchemaDef> = <
   M extends GetModels<Schema>,
   T extends object,
>(
   model: M,
   dto: Type<T>,
) => Type<object>;

/**
 * Constrains a customs map so each value is a {@link SchemaMappedTypeFn}
 * while preserving literal key names for overrides/extensions.
 *
 * @typeParam Schema - ZenStack schema definition.
 * @typeParam Customs - Customs object shape.
 */
export type CustomMappedTypes<Schema extends SchemaDef, Customs> = {
   [K in keyof Customs]: SchemaMappedTypeFn<Schema>;
};

/**
 * Binds each custom `(schema, model, dto)` factory to `Schema`, yielding `(model, dto)` helpers.
 *
 * @typeParam Schema - ZenStack schema definition.
 * @typeParam Customs - Map of custom mapped-type factories.
 */
export type BoundCustomMappedTypes<
   Schema extends SchemaDef,
   Customs extends CustomMappedTypes<Schema, Customs>,
> = {
   [K in keyof Customs]: <M extends GetModels<Schema>, T extends object>(
      model: M,
      dto: Type<T>,
   ) => ReturnType<Customs[K] extends SchemaMappedTypeFn<Schema> ? Customs[K] : never>;
};

function bindCustomMappedTypes<
   Schema extends SchemaDef,
   Customs extends CustomMappedTypes<Schema, Customs>,
>(schema: Schema, customs: Customs): BoundCustomMappedTypes<Schema, Customs> {
   const bound = {} as BoundCustomMappedTypes<Schema, Customs>;
   for (const key of Object.keys(customs as object) as Array<keyof Customs & string>) {
      const factory = customs[key] as SchemaMappedTypeFn<Schema>;
      bound[key] = ((model: GetModels<Schema>, dto: Type<object>) =>
         factory(schema, model, dto)) as BoundCustomMappedTypes<Schema, Customs>[typeof key];
   }
   return bound;
}

function createBuiltins<Schema extends SchemaDef>(schema: Schema) {
   return {
      /**
       * Omits relation fields for `model` from `dto`.
       * @see {@link OmitRelations}
       */
      omitRelations: <M extends GetModels<Schema>, T extends object>(model: M, dto: Type<T>) =>
         OmitRelations(schema, model, dto),
      /**
       * Picks only relation fields for `model` from `dto`.
       * @see {@link OnlyRelations}
       */
      onlyRelations: <M extends GetModels<Schema>, T extends object>(
         model: M,
         dto: TypeWithKeys<T, RelationFields<Schema, M>>,
      ) => OnlyRelations(schema, model, dto),
      /**
       * Picks only scalar fields for `model` from `dto`.
       * @see {@link OnlyScalars}
       */
      onlyScalars: <M extends GetModels<Schema>, T extends object>(
         model: M,
         dto: TypeWithKeys<T, ScalarFields<Schema, M>>,
      ) => OnlyScalars(schema, model, dto),
      /**
       * Omits scalar fields for `model` from `dto`.
       * @see {@link OmitScalars}
       */
      omitScalars: <M extends GetModels<Schema>, T extends object>(model: M, dto: Type<T>) =>
         OmitScalars(schema, model, dto),
      /**
       * Omits foreign-key fields for `model` from `dto`.
       * @see {@link OmitFK}
       */
      omitFK: <M extends GetModels<Schema>, T extends object>(model: M, dto: Type<T>) =>
         OmitFK(schema, model, dto),
      /**
       * Picks only foreign-key fields for `model` from `dto`.
       * @see {@link OnlyFK}
       */
      onlyFK: <M extends GetModels<Schema>, T extends object>(
         model: M,
         dto: TypeWithKeys<T, ForeignKeyFields<Schema, M>>,
      ) => OnlyFK(schema, model, dto),
      /**
       * Omits computed fields for `model` from `dto`.
       * @see {@link OmitComputed}
       */
      omitComputed: <M extends GetModels<Schema>, T extends object>(model: M, dto: Type<T>) =>
         OmitComputed(schema, model, dto),
      /**
       * Omits auto-generated fields for `model` from `dto`.
       * @see {@link OmitAutoGenerated}
       */
      omitAutoGenerated: <M extends GetModels<Schema>, T extends object>(model: M, dto: Type<T>) =>
         OmitAutoGenerated(schema, model, dto),
      /**
       * Omits primary-key fields for `model` from `dto`.
       * @see {@link OmitPK}
       */
      omitPK: <M extends GetModels<Schema>, T extends object>(model: M, dto: Type<T>) =>
         OmitPK(schema, model, dto),
      /**
       * Picks only primary-key fields for `model` from `dto`.
       * @see {@link OnlyPK}
       */
      onlyPK: <M extends GetModels<Schema>, T extends object>(
         model: M,
         dto: TypeWithKeys<T, PrimaryKeyFields<Schema, M>>,
      ) => OnlyPK(schema, model, dto),
      /**
       * Create-input mapped type for `model` (no computed / auto-generated / relations).
       * @see {@link CreateType}
       */
      createType: <M extends GetModels<Schema>, T extends object>(model: M, dto: Type<T>) =>
         CreateType(schema, model, dto),
      /**
       * Update-input mapped type for `model` (`CreateType` + `PartialType`).
       * @see {@link UpdateType}
       */
      updateType: <M extends GetModels<Schema>, T extends object>(model: M, dto: Type<T>) =>
         UpdateType(schema, model, dto),
      /**
       * Starts a type-safe mapped-type chain with `schema` already bound.
       * @see {@link chain}
       */
      chain: <M extends GetModels<Schema>, T extends object>(model: M, dto: Type<T>) =>
         chain(schema, model, dto),
   };
}

/**
 * Built-in helpers produced by {@link CreateMappedTypes} (before custom merges).
 *
 * @typeParam Schema - ZenStack schema definition.
 */
export type BuiltInMappedTypes<Schema extends SchemaDef> = ReturnType<typeof createBuiltins<Schema>>;

/**
 * Result of {@link CreateMappedTypes}: built-ins, with `Customs` keys overriding or extending them.
 *
 * @typeParam Schema - ZenStack schema definition.
 * @typeParam Customs - Optional custom / overriding mapped-type factories.
 */
export type MappedTypesApi<
   Schema extends SchemaDef,
   Customs extends CustomMappedTypes<Schema, Customs> = {},
> = Omit<BuiltInMappedTypes<Schema>, keyof Customs> & BoundCustomMappedTypes<Schema, Customs>;

/**
 * Identity helper that contextually types a customs map for {@link CreateMappedTypes}.
 *
 * Use this when defining inline factories so parameter types are inferred:
 *
 * @example
 * ```ts
 * const mapped = CreateMappedTypes(
 *   schema,
 *   mappedTypeCustoms(schema)({
 *     updateType: (schema, model, dto) => PartialType(OmitRelations(schema, model, dto)),
 *   }),
 * );
 * ```
 *
 * @typeParam Schema - ZenStack schema definition.
 * @param _schema - Schema instance (used only for typing).
 */
export function mappedTypeCustoms<Schema extends SchemaDef>(_schema: Schema) {
   return <Customs extends Record<string, SchemaMappedTypeFn<Schema>>>(customs: Customs): Customs =>
      customs;
}

/**
 * Binds a ZenStack `schema` once and returns schema-scoped mapped-type helpers
 * so callers do not pass `schema` on every call.
 *
 * Pass an optional `customs` map of `(schema, model, dto) => Type` factories to
 * add new helpers or override built-ins (e.g. a custom `updateType`).
 * Prefer {@link mappedTypeCustoms} when defining inline factories for full typing.
 *
 * @typeParam Schema - ZenStack schema definition.
 * @typeParam Customs - Optional custom / overriding mapped-type factories.
 * @param schema - Schema instance to close over.
 * @param customs - Optional map of factories to bind and merge onto the result.
 * @returns Helpers for omit/pick operations, {@link chain}, and any customs.
 *
 * @example
 * ```ts
 * const mapped = CreateMappedTypes(
 *   schema,
 *   mappedTypeCustoms(schema)({
 *     updateType: (schema, model, dto) =>
 *       PartialType(OmitRelations(schema, model, dto)),
 *     softDeleteType: (schema, model, dto) =>
 *       OmitPK(schema, model, dto),
 *   }),
 * );
 *
 * class UpdateUserDTO extends mapped.updateType("User", UserDTO) {}
 * class SoftDeleteUserDTO extends mapped.softDeleteType("User", UserDTO) {}
 * ```
 */
export function CreateMappedTypes<Schema extends SchemaDef>(
   schema: Schema,
): MappedTypesApi<Schema, {}>;
export function CreateMappedTypes<
   Schema extends SchemaDef,
   Customs extends CustomMappedTypes<Schema, Customs>,
>(schema: Schema, customs: Customs): MappedTypesApi<Schema, Customs>;
export function CreateMappedTypes<
   Schema extends SchemaDef,
   Customs extends CustomMappedTypes<Schema, Customs> = {},
>(schema: Schema, customs?: Customs): MappedTypesApi<Schema, Customs> {
   const builtins = createBuiltins(schema);

   if (!customs || Object.keys(customs as object).length === 0) {
      return builtins as MappedTypesApi<Schema, Customs>;
   }

   return {
      ...builtins,
      ...bindCustomMappedTypes(schema, customs),
   } as MappedTypesApi<Schema, Customs>;
}
