import { Type } from "@nestjs/common";
import { GetModels, SchemaDef } from "@zenstackhq/schema";
import { chain } from "./chain";
import { OmitAutoGenerated } from "./omit-auto-generated";
import { OmitComputed } from "./omit-computed";
import { OmitRelations } from "./omit-relations";

/**
 * Creates a Nest mapped type suitable for create input: omits computed fields,
 * auto-generated fields, and relations from `dto`.
 *
 * Foreign-key scalars (e.g. `userId`) are kept. Compatible with
 * {@link MappedTypeChain.pipe}.
 *
 * @typeParam Schema - ZenStack schema definition.
 * @typeParam M - Model name within `Schema`.
 * @typeParam T - DTO instance shape.
 * @param schema - Schema instance.
 * @param model - Model the DTO corresponds to.
 * @param dto - Source DTO class constructor.
 *
 * @example
 * ```ts
 * class CreateUserDTO extends CreateType(schema, "User", UserDTO) {}
 * ```
 */
export function CreateType<Schema extends SchemaDef, M extends GetModels<Schema>, T extends object>(
   schema: Schema,
   model: M,
   dto: Type<T>,
) {
   return chain(schema, model, dto).pipe(OmitComputed).pipe(OmitAutoGenerated).pipe(OmitRelations).build();
}
