import {
   ForeignKeyFields,
   GetModels,
   RelationFields,
   ScalarFields,
   SchemaDef,
   type FieldDef,
} from "@zenstackhq/schema";
import { AutoGeneratedFields, ComputedFields, PrimaryKeyFields } from "./types";

function getFieldNames<Schema extends SchemaDef, M extends GetModels<Schema>, K extends string>(
   schema: Schema,
   model: M,
   predicate: (field: FieldDef) => boolean,
): K[] {
   return Object.values(schema.models[model].fields)
      .filter(predicate)
      .map((field) => field.name) as K[];
}

/**
 * Returns the relation field names for `model` (fields with a `relation` definition).
 *
 * @typeParam Schema - ZenStack schema definition.
 * @typeParam M - Model name within `Schema`.
 * @param schema - Schema instance.
 * @param model - Model whose fields to inspect.
 */
export function getRelationFieldsOfModel<Schema extends SchemaDef, M extends GetModels<Schema>>(
   schema: Schema,
   model: M,
): RelationFields<Schema, M>[] {
   return getFieldNames(schema, model, (field) => field.relation !== undefined);
}

/**
 * Returns the scalar field names for `model` (excludes relations and foreign keys).
 *
 * @typeParam Schema - ZenStack schema definition.
 * @typeParam M - Model name within `Schema`.
 * @param schema - Schema instance.
 * @param model - Model whose fields to inspect.
 */
export function getScalarFieldsOfModel<Schema extends SchemaDef, M extends GetModels<Schema>>(
   schema: Schema,
   model: M,
): ScalarFields<Schema, M>[] {
   return getFieldNames(
      schema,
      model,
      (field) => field.relation == undefined && field.foreignKeyFor == undefined,
   );
}

/**
 * Returns the foreign-key field names for `model` (fields with `foreignKeyFor`).
 *
 * @typeParam Schema - ZenStack schema definition.
 * @typeParam M - Model name within `Schema`.
 * @param schema - Schema instance.
 * @param model - Model whose fields to inspect.
 */
export function getForeignKeyFieldsOfModel<Schema extends SchemaDef, M extends GetModels<Schema>>(
   schema: Schema,
   model: M,
): ForeignKeyFields<Schema, M>[] {
   return getFieldNames(schema, model, (field) => field.foreignKeyFor !== undefined);
}

/**
 * Returns the computed field names for `model` (`computed: true`).
 *
 * @typeParam Schema - ZenStack schema definition.
 * @typeParam M - Model name within `Schema`.
 * @param schema - Schema instance.
 * @param model - Model whose fields to inspect.
 */
export function getComputedFieldsOfModel<Schema extends SchemaDef, M extends GetModels<Schema>>(
   schema: Schema,
   model: M,
): ComputedFields<Schema, M>[] {
   return getFieldNames(schema, model, (field) => field.computed === true);
}

/**
 * Returns auto-generated field names for `model` — fields with a `default`,
 * `updatedAt`, or relation `hasDefault`.
 *
 * @typeParam Schema - ZenStack schema definition.
 * @typeParam M - Model name within `Schema`.
 * @param schema - Schema instance.
 * @param model - Model whose fields to inspect.
 */
export function getAutoGeneratedFieldsOfModel<Schema extends SchemaDef, M extends GetModels<Schema>>(
   schema: Schema,
   model: M,
): AutoGeneratedFields<Schema, M>[] {
   return getFieldNames(
      schema,
      model,
      (field) =>
         field.default !== undefined ||
         field.updatedAt !== undefined ||
         field.relation?.hasDefault === true,
   );
}

/**
 * Returns the primary-key field names for `model` from `idFields`
 * (including compound keys).
 *
 * @typeParam Schema - ZenStack schema definition.
 * @typeParam M - Model name within `Schema`.
 * @param schema - Schema instance.
 * @param model - Model whose primary key to read.
 */
export function getPrimaryKeyFieldsOfModel<Schema extends SchemaDef, M extends GetModels<Schema>>(
   schema: Schema,
   model: M,
): PrimaryKeyFields<Schema, M>[] {
   return [...schema.models[model].idFields] as PrimaryKeyFields<Schema, M>[];
}
