import { Type } from "@nestjs/common";
import { GetModels, SchemaDef } from "@zenstackhq/schema";
import { getAutoGeneratedFieldsOfModel } from "./functions";
import { omitDtoKeys } from "./dto-keys";

/**
 * Creates a Nest mapped type from `dto` with auto-generated fields omitted
 * (defaults, `@updatedAt`, relation `hasDefault`).
 *
 * Compatible with {@link MappedTypeChain.pipe}.
 *
 * @typeParam Schema - ZenStack schema definition.
 * @typeParam M - Model name within `Schema`.
 * @typeParam T - DTO instance shape.
 * @param schema - Schema instance.
 * @param model - Model whose auto-generated fields to omit.
 * @param dto - Source DTO class constructor.
 */
export function OmitAutoGenerated<
   Schema extends SchemaDef,
   M extends GetModels<Schema>,
   T extends object,
>(schema: Schema, model: M, dto: Type<T>) {
   return omitDtoKeys(dto, getAutoGeneratedFieldsOfModel(schema, model));
}
