import { Type } from "@nestjs/common";
import {
   FieldHasDefault,
   FieldIsComputed,
   GetModel,
   GetModelFields,
   GetModels,
   SchemaDef,
} from "@zenstackhq/schema";

/**
 * `true` when every key in `K` exists on `T` (optional or required).
 *
 * @typeParam T - Object type to inspect.
 * @typeParam K - Keys that must exist on `T`.
 */
export type HasKeys<T, K extends PropertyKey> = [K] extends [keyof T] ? true : false;

/**
 * Compile-time error message listing keys from `K` that are missing on `T`.
 *
 * @typeParam T - Object type being checked.
 * @typeParam K - Required keys.
 */
export type MissingKeysError<T, K extends PropertyKey> =
   `Type is missing keys: ${Exclude<K, keyof T> & string}`;

/**
 * Resolves to Nest's {@link Type}`<T>` when every key in `K` exists on `T`
 * (optional or required). Otherwise resolves to {@link MissingKeysError}.
 *
 * Useful for constraining DTO class refs passed to pick-style mapped types.
 *
 * @typeParam T - DTO instance shape.
 * @typeParam K - Keys that must exist on `T`.
 */
export type TypeWithKeys<T, K extends PropertyKey> =
   HasKeys<T, K> extends true ? Type<T> : MissingKeysError<T, K>;

/**
 * Field names on `Model` that are marked `computed: true` in the schema.
 *
 * @typeParam Schema - ZenStack schema definition.
 * @typeParam Model - Model name within `Schema`.
 */
export type ComputedFields<Schema extends SchemaDef, Model extends GetModels<Schema>> = keyof {
   [Key in GetModelFields<Schema, Model> as FieldIsComputed<Schema, Model, Key> extends true
      ? Key
      : never]: Key;
};

/**
 * Field names on `Model` that ZenStack treats as having a default
 * (`FieldHasDefault`) — typically `@default`, `@updatedAt`, or relation
 * `hasDefault`.
 *
 * @typeParam Schema - ZenStack schema definition.
 * @typeParam Model - Model name within `Schema`.
 */
export type AutoGeneratedFields<Schema extends SchemaDef, Model extends GetModels<Schema>> = keyof {
   [Key in GetModelFields<Schema, Model> as FieldHasDefault<Schema, Model, Key> extends true
      ? Key
      : never]: Key;
};

/**
 * Primary-key field names for `Model`, taken from the model's `idFields`
 * (supports compound primary keys).
 *
 * @typeParam Schema - ZenStack schema definition.
 * @typeParam Model - Model name within `Schema`.
 */
export type PrimaryKeyFields<
   Schema extends SchemaDef,
   Model extends GetModels<Schema>,
> = Extract<GetModel<Schema, Model>["idFields"][number], GetModelFields<Schema, Model>>;
